targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/firestore_ref_model/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/firestore_ref_model/*.dart
